# Generated by Django 5.2.6 on 2025-09-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lai_app', '0002_cidadao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidadao',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='num_doc_id',
            field=models.CharField(max_length=20, verbose_name='Documento de Identificação'),
        ),
        migrations.AlterField(
            model_name='cidadao',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_adm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setor_adm', to='lai_app.setor', verbose_name='Setor Administrativo')),
                ('setor_parecer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setor_parecer', to='lai_app.setor', verbose_name='Setor Emissor de Parecer')),
                ('setor_recurso_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setor_recurso_1', to='lai_app.setor', verbose_name='Setor do Responsável pelo Recurso em 1ª Instância')),
                ('setor_recurso_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setor_recurso_2', to='lai_app.setor', verbose_name='Setor do Responsável pelo Recurso em 2ª Instância')),
                ('setor_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setor_resposta', to='lai_app.setor', verbose_name='Setor Emissor de Resposta')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='PedidoInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('AI', 'Análise Inicial'), ('BI', 'Buscando Informações'), ('EP', 'Elaborando Parecer'), ('DR', 'Definindo Resposta'), ('PR', 'Pedido Respondido'), ('AR', 'Analisando Recurso'), ('RR', 'Recurso Respondido'), ('AF', 'Analisando Recurso Final'), ('RF', 'Recurso Final Respondido')], default='AI', max_length=2, verbose_name='Situação')),
                ('num_registro', models.PositiveIntegerField(unique_for_year=True, verbose_name='Número de Registro')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_encam', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encaminhamento')),
                ('arquivo_info', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Caminho do Arquivo')),
                ('observacoes_forn', models.TextField(blank=True, null=True)),
                ('data_fornec', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fornecimento da Informação')),
                ('parecer', models.TextField(blank=True, null=True)),
                ('data_parecer', models.DateTimeField(blank=True, null=True, verbose_name='Data do Parecer')),
                ('resp_inicial', models.BooleanField(default=False, verbose_name='Resposta Inicial')),
                ('just_resp_inicial', models.TextField(blank=True, null=True, verbose_name='Justificativa da Resposta Inicial')),
                ('data_resp_inicial', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta Inicial')),
                ('recurso_1', models.TextField(blank=True, null=True, verbose_name='Recurso em 1ª Instância')),
                ('data_recurso_1', models.DateTimeField(blank=True, null=True, verbose_name='Data do Recurso em 1ª Instância')),
                ('resp_recurso_1', models.BooleanField(default=False, verbose_name='Resposta ao Recurso em 1ª Instância')),
                ('just_resp_recurso_1', models.TextField(blank=True, null=True, verbose_name='Justificativa da Resposta ao Recurso em 1ª Instância')),
                ('data_resp_recurso_1', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta ao Recurso em 1ª Instância')),
                ('recurso_2', models.TextField(blank=True, null=True, verbose_name='Recurso em 2ª Instância')),
                ('data_recurso_2', models.DateTimeField(blank=True, null=True, verbose_name='Data do Recurso em 2ª Instância')),
                ('resp_recurso_2', models.BooleanField(default=False, verbose_name='Resposta ao Recurso em 2ª Instância')),
                ('just_resp_recurso_2', models.TextField(blank=True, null=True, verbose_name='Justificativa da Resposta ao Recurso em 2ª Instância')),
                ('data_resp_recurso_2', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta ao Recurso em 2ª Instância')),
                ('func_adm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_adm', to='lai_app.funcionario', verbose_name='Funcionário do Setor Administrativo')),
                ('func_fornec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_fornec', to='lai_app.funcionario', verbose_name='Funcionário do Setor Fornecedor')),
                ('func_parecer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_parecer', to='lai_app.funcionario', verbose_name='Funcionário do Setor Emissor do Parecer')),
                ('func_resp_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_resp_inicial', to='lai_app.funcionario', verbose_name='Funcionário Emissor da Resposta Inicial')),
                ('func_resp_recurso_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_resp_recurso_1', to='lai_app.funcionario', verbose_name='Funcionário da Resposta ao Recurso em 1ª Instância')),
                ('func_resp_recurso_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='func_resp_recurso_2', to='lai_app.funcionario', verbose_name='Funcionário da Resposta ao Recurso em 2ª Instância')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cid_req', to='lai_app.cidadao', verbose_name='Requerente')),
                ('setor_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lai_app.setor', verbose_name='Setor Fornecedor da Informação')),
            ],
            options={
                'verbose_name': 'Pedido de Informação',
                'verbose_name_plural': 'Pedidos de Informação',
            },
        ),
    ]
