# Generated by Django 5.2.6 on 2025-09-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lai_app', '0003_alter_cidadao_cep_alter_cidadao_num_doc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidadao',
            name='ativo',
        ),
    ]
