# Generated by Django 5.2.6 on 2025-09-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lai_app', '0004_remove_cidadao_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoinformacao',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoinformacao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pedidoinformacao',
            name='just_resp_inicial',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='pedidoinformacao',
            name='observacoes_forn',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='pedidoinformacao',
            name='resp_inicial',
            field=models.BooleanField(default=False, verbose_name='Pedido Deferido?'),
        ),
        migrations.AlterField(
            model_name='pedidoinformacao',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
