# Generated by Django 5.2.6 on 2025-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lai_app', '0005_alter_pedidoinformacao_data_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoinformacao',
            name='prazo_recurso_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo para Recurso em 1ª Instância'),
        ),
    ]
