# Generated by Django 5.2.6 on 2025-09-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lai_app', '0006_pedidoinformacao_prazo_recurso_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoinformacao',
            name='prazo_recurso_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo para Recurso em 2ª Instância'),
        ),
    ]
